[package]
name = "3frac"
version = "0.1.0"
authors = ["Nathan Perry <avaglir@gmail.com>"]

[dependencies]
kiss3d = "0.13"
failure = "0.1"
nalgebra = "0.14"
glfw = "0.19"
itertools = "0.7"
ncollide = "0.14"
lazy_static = "1.0"
alga = "0.5.3"
palette = "0.3"
